### ISSUE TITLE
: Failed to load nodelet [/TrackingNodeletClass_loader] of type [flvis/TrackingNodeletClass] even after refreshing the cache: 

### ISSUE THREAD

**Issue by wkyouncnu** [Ttoto/FLVIS#11]
I have the following issues when running flvis.lauch files

wkyoun@wkyoun:~/catkin_ws/src/FLVIS/3rdPartLib$ roslaunch flvis flvis_bag.launch

```
... logging to /home/wkyoun/.ros/log/e21125fe-f4e7-11eb-a66b-f83441d19d8b/roslaunch-wkyoun-3680.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
WARNING: disk usage in log directory [/home/wkyoun/.ros/log] is over 1GB.
It's recommended that you use the 'rosclean' command.

started roslaunch server http://localhost:34925/

SUMMARY
========

PARAMETERS
 * /LocalMapNodeletClass_loader/window_size: 8
 * /flvis_nodelet_manager/num_worker_threads: 4
 * /rosdistro: melodic
 * /rosversion: 1.14.6
 * /voc: /home/wkyoun/catk...
 * /yamlconfigfile: /home/wkyoun/catk...

NODES
  /
    LocalMapNodeletClass_loader (nodelet/nodelet)
    LoopClosingNodeletClass_loader (nodelet/nodelet)
    TrackingNodeletClass_loader (nodelet/nodelet)
    flvis_nodelet_manager (nodelet/nodelet)
    rosbag (rosbag/play)

ROS_MASTER_URI=http://localhost:11311

process[rosbag-1]: started with pid [3695]
process[flvis_nodelet_manager-2]: started with pid [3696]
process[TrackingNodeletClass_loader-3]: started with pid [3699]
process[LocalMapNodeletClass_loader-4]: started with pid [3704]
process[LoopClosingNodeletClass_loader-5]: started with pid [3707]
[ INFO] [1628058548.304574097]: Loading nodelet /TrackingNodeletClass_loader of type flvis/TrackingNodeletClass to manager flvis_nodelet_manager with the following remappings:
[ INFO] [1628058548.306047645]: /imu -> /camera/imu
[ INFO] [1628058548.306077851]: /vo/input_image_0 -> /camera/infra1/image_rect_raw
[ INFO] [1628058548.306099428]: /vo/input_image_1 -> /camera/aligned_depth_to_infra1/image_raw
[ INFO] [1628058548.308495280]: waitForService: Service [/flvis_nodelet_manager/load_nodelet] has not been advertised, waiting...
[ INFO] [1628058548.310410738]: Loading nodelet /LocalMapNodeletClass_loader of type flvis/LocalMapNodeletClass to manager flvis_nodelet_manager with the following remappings:
[ INFO] [1628058548.313362045]: waitForService: Service [/flvis_nodelet_manager/load_nodelet] has not been advertised, waiting...
[ INFO] [1628058548.315448631]: Loading nodelet /LoopClosingNodeletClass_loader of type flvis/LoopClosingNodeletClass to manager flvis_nodelet_manager with the following remappings:
[ INFO] [1628058548.316921077]: waitForService: Service [/flvis_nodelet_manager/load_nodelet] has not been advertised, waiting...
[ INFO] [1628058548.325498208]: Initializing nodelet with 4 worker threads.
[ INFO] [1628058548.329834500]: waitForService: Service [/flvis_nodelet_manager/load_nodelet] is now available.
[ INFO] [1628058548.334870470]: waitForService: Service [/flvis_nodelet_manager/load_nodelet] is now available.
[ INFO] [1628058548.338557993]: waitForService: Service [/flvis_nodelet_manager/load_nodelet] is now available.

**[ERROR] [1628058548.348605360]: Failed to load nodelet [/TrackingNodeletClass_loader] of type [flvis/TrackingNodeletClass] even after refreshing the cache: Failed to load library /home/wkyoun/catkin_ws/devel/lib//libflvis.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libg2o_opengl_helper.so: cannot open shared object file: No such file or directory)
[ERROR] [1628058548.348633783]: The error before refreshing the cache was: Failed to load library** /home/wkyoun/catkin_ws/devel/lib//libflvis.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libg2o_opengl_helper.so: cannot open shared object file: No such file or directory)
[FATAL] [1628058548.348761256]: Failed to load nodelet '/TrackingNodeletClass_loader` of type `flvis/TrackingNodeletClass` to manager `flvis_nodelet_manager'
[ERROR] [1628058548.363892138]: Failed to load nodelet [/LocalMapNodeletClass_loader] of type [flvis/LocalMapNodeletClass] even after refreshing the cache: Failed to load library /home/wkyoun/catkin_ws/devel/lib//libflvis.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libg2o_opengl_helper.so: cannot open shared object file: No such file or directory)**
[ERROR] [1628058548.363918278]: The error before refreshing the cache was: Failed to load library /home/wkyoun/catkin_ws/devel/lib//libflvis.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libg2o_opengl_helper.so: cannot open shared object file: No such file or directory)
[FATAL] [1628058548.364013669]: Failed to load nodelet '/LocalMapNodeletClass_loader` of type `flvis/LocalMapNodeletClass` to manager `flvis_nodelet_manager'
[ERROR] [1628058548.379130266]: Failed to load nodelet [/LoopClosingNodeletClass_loader] of type [flvis/LoopClosingNodeletClass] even after refreshing the cache: Failed to load library /home/wkyoun/catkin_ws/devel/lib//libflvis.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libg2o_opengl_helper.so: cannot open shared object file: No such file or directory)
[ERROR] [1628058548.379160131]: The error before refreshing the cache was: Failed to load library /home/wkyoun/catkin_ws/devel/lib//libflvis.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libg2o_opengl_helper.so: cannot open shared object file: No such file or directory)
[FATAL] [1628058548.379301086]: Failed to load nodelet '/LoopClosingNodeletClass_loader` of type `flvis/LoopClosingNodeletClass` to manager `flvis_nodelet_manager'
[TrackingNodeletClass_loader-3] process has died [pid 3699, exit code 255, cmd bash -c sleep 1.0; $0 $@ /opt/ros/melodic/lib/nodelet/nodelet load flvis/TrackingNodeletClass flvis_nodelet_manager /vo/input_image_0:=/camera/infra1/image_rect_raw /vo/input_image_1:=/camera/aligned_depth_to_infra1/image_raw /imu:=/camera/imu __name:=TrackingNodeletClass_loader __log:=/home/wkyoun/.ros/log/e21125fe-f4e7-11eb-a66b-f83441d19d8b/TrackingNodeletClass_loader-3.log].
log file: /home/wkyoun/.ros/log/e21125fe-f4e7-11eb-a66b-f83441d19d8b/TrackingNodeletClass_loader-3*.log
[LocalMapNodeletClass_loader-4] process has died [pid 3704, exit code 255, cmd bash -c sleep 1.0; $0 $@ /opt/ros/melodic/lib/nodelet/nodelet load flvis/LocalMapNodeletClass flvis_nodelet_manager __name:=LocalMapNodeletClass_loader __log:=/home/wkyoun/.ros/log/e21125fe-f4e7-11eb-a66b-f83441d19d8b/LocalMapNodeletClass_loader-4.log].
log file: /home/wkyoun/.ros/log/e21125fe-f4e7-11eb-a66b-f83441d19d8b/LocalMapNodeletClass_loader-4*.log
[LoopClosingNodeletClass_loader-5] process has died [pid 3707, exit code 255, cmd bash -c sleep 1.0; $0 $@ /opt/ros/melodic/lib/nodelet/nodelet load flvis/LoopClosingNodeletClass flvis_nodelet_manager __name:=LoopClosingNodeletClass_loader __log:=/home/wkyoun/.ros/log/e21125fe-f4e7-11eb-a66b-f83441d19d8b/LoopClosingNodeletClass_loader-5.log].
log file: /home/wkyoun/.ros/log/e21125fe-f4e7-11eb-a66b-f83441d19d8b/LoopClosingNodeletClass_loader-5*.log
^C[flvis_nodelet_manager-2] killing on exit
[rosbag-1] killing on exit
shutting down processing monitor...''
... shutting down processing monitor complete
done
```

**Comment by Ttoto** [comment]
It looks wired. 
Which ROS Distro were you used?
Can you paste the output of `catkin_make`

**Comment by JazzyFeng** [comment]
> I have the following issues when running flvis.lauch files
> 
> wkyoun@wkyoun:~/catkin_ws/src/FLVIS/3rdPartLib$ roslaunch flvis flvis_bag.launch
> 
> ```
> ... logging to /home/wkyoun/.ros/log/e21125fe-f4e7-11eb-a66b-f83441d19d8b/roslaunch-wkyoun-3680.log
> Checking log directory for disk usage. This may take a while.
> Press Ctrl-C to interrupt
> WARNING: disk usage in log directory [/home/wkyoun/.ros/log] is over 1GB.
> It's recommended that you use the 'rosclean' command.
> 
> started roslaunch server http://localhost:34925/
> 
> SUMMARY
> ========
> 
> PARAMETERS
>  * /LocalMapNodeletClass_loader/window_size: 8
>  * /flvis_nodelet_manager/num_worker_threads: 4
>  * /rosdistro: melodic
>  * /rosversion: 1.14.6
>  * /voc: /home/wkyoun/catk...
>  * /yamlconfigfile: /home/wkyoun/catk...
> 
> NODES
>   /
>     LocalMapNodeletClass_loader (nodelet/nodelet)
>     LoopClosingNodeletClass_loader (nodelet/nodelet)
>     TrackingNodeletClass_loader (nodelet/nodelet)
>     flvis_nodelet_manager (nodelet/nodelet)
>     rosbag (rosbag/play)
> 
> ROS_MASTER_URI=http://localhost:11311
> 
> process[rosbag-1]: started with pid [3695]
> process[flvis_nodelet_manager-2]: started with pid [3696]
> process[TrackingNodeletClass_loader-3]: started with pid [3699]
> process[LocalMapNodeletClass_loader-4]: started with pid [3704]
> process[LoopClosingNodeletClass_loader-5]: started with pid [3707]
> [ INFO] [1628058548.304574097]: Loading nodelet /TrackingNodeletClass_loader of type flvis/TrackingNodeletClass to manager flvis_nodelet_manager with the following remappings:
> [ INFO] [1628058548.306047645]: /imu -> /camera/imu
> [ INFO] [1628058548.306077851]: /vo/input_image_0 -> /camera/infra1/image_rect_raw
> [ INFO] [1628058548.306099428]: /vo/input_image_1 -> /camera/aligned_depth_to_infra1/image_raw
> [ INFO] [1628058548.308495280]: waitForService: Service [/flvis_nodelet_manager/load_nodelet] has not been advertised, waiting...
> [ INFO] [1628058548.310410738]: Loading nodelet /LocalMapNodeletClass_loader of type flvis/LocalMapNodeletClass to manager flvis_nodelet_manager with the following remappings:
> [ INFO] [1628058548.313362045]: waitForService: Service [/flvis_nodelet_manager/load_nodelet] has not been advertised, waiting...
> [ INFO] [1628058548.315448631]: Loading nodelet /LoopClosingNodeletClass_loader of type flvis/LoopClosingNodeletClass to manager flvis_nodelet_manager with the following remappings:
> [ INFO] [1628058548.316921077]: waitForService: Service [/flvis_nodelet_manager/load_nodelet] has not been advertised, waiting...
> [ INFO] [1628058548.325498208]: Initializing nodelet with 4 worker threads.
> [ INFO] [1628058548.329834500]: waitForService: Service [/flvis_nodelet_manager/load_nodelet] is now available.
> [ INFO] [1628058548.334870470]: waitForService: Service [/flvis_nodelet_manager/load_nodelet] is now available.
> [ INFO] [1628058548.338557993]: waitForService: Service [/flvis_nodelet_manager/load_nodelet] is now available.
> 
> **[ERROR] [1628058548.348605360]: Failed to load nodelet [/TrackingNodeletClass_loader] of type [flvis/TrackingNodeletClass] even after refreshing the cache: Failed to load library /home/wkyoun/catkin_ws/devel/lib//libflvis.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libg2o_opengl_helper.so: cannot open shared object file: No such file or directory)
> [ERROR] [1628058548.348633783]: The error before refreshing the cache was: Failed to load library** /home/wkyoun/catkin_ws/devel/lib//libflvis.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libg2o_opengl_helper.so: cannot open shared object file: No such file or directory)
> [FATAL] [1628058548.348761256]: Failed to load nodelet '/TrackingNodeletClass_loader` of type `flvis/TrackingNodeletClass` to manager `flvis_nodelet_manager'
> [ERROR] [1628058548.363892138]: Failed to load nodelet [/LocalMapNodeletClass_loader] of type [flvis/LocalMapNodeletClass] even after refreshing the cache: Failed to load library /home/wkyoun/catkin_ws/devel/lib//libflvis.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libg2o_opengl_helper.so: cannot open shared object file: No such file or directory)**
> [ERROR] [1628058548.363918278]: The error before refreshing the cache was: Failed to load library /home/wkyoun/catkin_ws/devel/lib//libflvis.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libg2o_opengl_helper.so: cannot open shared object file: No such file or directory)
> [FATAL] [1628058548.364013669]: Failed to load nodelet '/LocalMapNodeletClass_loader` of type `flvis/LocalMapNodeletClass` to manager `flvis_nodelet_manager'
> [ERROR] [1628058548.379130266]: Failed to load nodelet [/LoopClosingNodeletClass_loader] of type [flvis/LoopClosingNodeletClass] even after refreshing the cache: Failed to load library /home/wkyoun/catkin_ws/devel/lib//libflvis.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libg2o_opengl_helper.so: cannot open shared object file: No such file or directory)
> [ERROR] [1628058548.379160131]: The error before refreshing the cache was: Failed to load library /home/wkyoun/catkin_ws/devel/lib//libflvis.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libg2o_opengl_helper.so: cannot open shared object file: No such file or directory)
> [FATAL] [1628058548.379301086]: Failed to load nodelet '/LoopClosingNodeletClass_loader` of type `flvis/LoopClosingNodeletClass` to manager `flvis_nodelet_manager'
> [TrackingNodeletClass_loader-3] process has died [pid 3699, exit code 255, cmd bash -c sleep 1.0; $0 $@ /opt/ros/melodic/lib/nodelet/nodelet load flvis/TrackingNodeletClass flvis_nodelet_manager /vo/input_image_0:=/camera/infra1/image_rect_raw /vo/input_image_1:=/camera/aligned_depth_to_infra1/image_raw /imu:=/camera/imu __name:=TrackingNodeletClass_loader __log:=/home/wkyoun/.ros/log/e21125fe-f4e7-11eb-a66b-f83441d19d8b/TrackingNodeletClass_loader-3.log].
> log file: /home/wkyoun/.ros/log/e21125fe-f4e7-11eb-a66b-f83441d19d8b/TrackingNodeletClass_loader-3*.log
> [LocalMapNodeletClass_loader-4] process has died [pid 3704, exit code 255, cmd bash -c sleep 1.0; $0 $@ /opt/ros/melodic/lib/nodelet/nodelet load flvis/LocalMapNodeletClass flvis_nodelet_manager __name:=LocalMapNodeletClass_loader __log:=/home/wkyoun/.ros/log/e21125fe-f4e7-11eb-a66b-f83441d19d8b/LocalMapNodeletClass_loader-4.log].
> log file: /home/wkyoun/.ros/log/e21125fe-f4e7-11eb-a66b-f83441d19d8b/LocalMapNodeletClass_loader-4*.log
> [LoopClosingNodeletClass_loader-5] process has died [pid 3707, exit code 255, cmd bash -c sleep 1.0; $0 $@ /opt/ros/melodic/lib/nodelet/nodelet load flvis/LoopClosingNodeletClass flvis_nodelet_manager __name:=LoopClosingNodeletClass_loader __log:=/home/wkyoun/.ros/log/e21125fe-f4e7-11eb-a66b-f83441d19d8b/LoopClosingNodeletClass_loader-5.log].
> log file: /home/wkyoun/.ros/log/e21125fe-f4e7-11eb-a66b-f83441d19d8b/LoopClosingNodeletClass_loader-5*.log
> ^C[flvis_nodelet_manager-2] killing on exit
> [rosbag-1] killing on exit
> shutting down processing monitor...''
> ... shutting down processing monitor complete
> done
> ```

I guess the problem can be solved by 
````
sudo ldconfig
````

**Comment by chenhanpolyu** [comment]
@wkyouncnu I solve this issue by cleaning the workspace and compiling the package again.
