### ISSUE TITLE
[FATAL] [1632737727.144338183]: Failed to load nodelet '/LoopClosingNodeletClass_loader` of type `flvis/LoopClosingNodeletClass` to manager `flvis_nodelet_manager'

### ISSUE THREAD

**Issue by pallavbhalla** [Ttoto/FLVIS#12]
While testing FLVIS, I faced this  issue, where I am not able to load the loop closing nodelet, while the other nodelets are able to load. Any ideas why? The program crashes in runtime. 
I am running it on ROS melodic.

**Comment by pallavbhalla** [comment]
I am working with E2ES simulator and was using the defined procedure in README.md. I was getting this error because the params corresponding to LoopClosureThread were not configured in the [CONFIG](https://github.com/HKPolyU-UAV/E2ES/blob/master/launch/config/flvis_e2es.yaml) file inside the e2es simulation.

**Comment by Ttoto** [comment]
> I am working with E2ES simulator and was using the defined procedure in README.md. I was getting this error because the params corresponding to LoopClosureThread were not configured in the [CONFIG](https://github.com/HKPolyU-UAV/E2ES/blob/master/launch/config/flvis_e2es.yaml) file inside the e2es simulation.

Thank you for your feedback. If u use the FLVIS with the E2ES. We suggest you disable the loop closing feature for two reasons:
1, The pose estimation is accurate enough for most applications (<1% drift in the simulator)
2, As we use the same wallpaper in the simulation world. This might lead to a mismatch of loop closure.

**Comment by darshan-kt** [comment]
I resolved this issue by installing the libg20 library.
$ sudo apt-get install ros-melodic-libg2o
