### ISSUE TITLE
The program may exit early with an error when you play the bag at 2X speed

### ISSUE THREAD

**Issue by chenhanpolyu** [Ttoto/FLVIS#13]
I just want to report the solutions to an issue when you test FLVIS with rosbag:
`tracking: 112|119|156
tracking: 105|111|157
tracking: 102|116|166
tracking: 98|107|167
tracking: 81|87|147
tracking: 60|70|160
tracking: 65|70|155
tracking: 34|41|141
tracking: 43|104|140
tracking: 9|89|139
[Critical Warning] Tracking Fail-no enough lm pairs
tracking: 7|63|141
[Critical Warning] Tracking Fail-no enough lm pairs
Tracking failed! Swith to tracking Fail Mode
vision tracking fail, IMU motion only
Tring to recover~
[Critical Warning]: motion not in queue! please enlarge the buffer size
/opt/ros/melodic/lib/nodelet/nodelet: line 1: 29821 Segmentation fault      (core dumped) $0 $@
[flvis_nodelet_manager-3] process has died [pid 29819, exit code 139, cmd bash -c sleep 0; $0 $@ /opt/ros/melodic/lib/nodelet/nodelet manager __name:=flvis_nodelet_manager __log:=/home/zuzu/.ros/log/54a07096-71c2-11ec-8464-c8e2650adb10/flvis_nodelet_manager-3.log].
log file: /home/zuzu/.ros/log/54a07096-71c2-11ec-8464-c8e2650adb10/flvis_nodelet_manager-3*.log
^C[TrackingNodeletClass_loader-4] killing on exit
[rosbag-2] killing on exit
[ INFO] [1641784028.984848051]: Unloading nodelet /TrackingNodeletClass_loader from manager flvis_nodelet_manager
[ INFO] [1641784028.985259802]: waitForService: Service [/flvis_nodelet_manager/unload_nodelet] could not connect to host [zuzu-MS-7C75:40729], waiting...
[ WARN] [1641784028.985274043]: Couldn't find service flvis_nodelet_manager/unload_nodelet, perhaps the manager is already shut down
`
This issue happens when you use flvis with only stereo mode (no imu data is input). Two solutions can be worthy to try:
**1. In the .yaml config file, tune the three parameters:**
#goodFeaturesToTrack detector maxCorners
feature_para4: 500 (increase it, i.g to 1000) 
#goodFeaturesToTrack detector qualityLevel
feature_para5: 0.005 (decrease)
#goodFeaturesToTrack detector minDistance
feature_para6: 5 (decrease)
These params can help to detect more features, while the requirements for the feature quality may be loosened.
2. Play the bag at a lower speed (the default speed in the launch file is 2.0 times faster than the original speed).

**Comment by JazzyFeng** [comment]
> 

Thanks for your report.

**Comment by JazzyFeng** [comment]
The solution is reported as @chenhanpolyu
