### ISSUE TITLE
Where does loop closing feed back to the algorithm?

### ISSUE THREAD

**Issue by antithing** [Ttoto/FLVIS#15]
Hi, I have this code running on Windows, and have removed the ROS dependency. It runs very well, but I cannot see how the loop closing feeds back to the local map, or the tracking. 

I can see that the local mapping feeds back to the tracking here:

```
void F2FTracking::correction_feed(const double time, const CorrectionInfStruct corr)
{
  this->correction_inf = corr;
  this->has_localmap_feedback = true;
}
```

After the loop closing thread does global optimization, how does this feed back to adjust the local map / tracking?

Thank you!

**Comment by JazzyFeng** [comment]
@antithing Loop closure thread is totally independent of tracking and local mapping thread. It does not feed back to these two threads.

**Comment by antithing** [comment]
Okay thank you! understood. I have tracking and mapping running well, but i notice that the relocalization is not great, often relocating to the incorrect position. Does this use BOW? or the IMU only? Thanks!

**Comment by JazzyFeng** [comment]
> Okay thank you! understood. I have tracking and mapping running well, but i notice that the relocalization is not great, often relocating to the incorrect position. Does this use BOW? or the IMU only? Thanks!

we use IMU only.
