### ISSUE TITLE
Is this suitable for mobile robots with only three degree of freedom?

### ISSUE THREAD

**Issue by YiChenCityU** [Ttoto/FLVIS#2]
Because there is little bit change of pitch and roll on mobile robot, the visual estimation with orientation feedforward (in purple) may not work. Am I right?

**Comment by Ttoto** [comment]
nope, It can work on the mobile robot platfrom. 
see: https://www.youtube.com/watch?v=IprouW6-tVM&t=5s
The purple part compensates the initial guess through feeding the "roll" and "pitch" part of the IMU pose to the visual workflow.

**Comment by YiChenCityU** [comment]
Thanks for your reply.

**Comment by zouyajing** [comment]
For ground mobile robot, we add planar motion constraint. It is not open-sourced yet.
