### ISSUE TITLE
Could this be a bug?

### ISSUE THREAD

**Issue by rocomanmelli** [Ttoto/FLVIS#4]
https://github.com/Ttoto/FLVIS/blob/7e83b3bf42a32de3637d9b5f05ec99ff63020f0e/src/frontend/vi_motion.cpp#L328

I would have expected this line to be something like: `gyro_bias =  (1-para_4)*gyro_bias+(para_4)*gyro_bias_est;`. Could you please confirm if this is a mistake or not?

**Comment by Ttoto** [comment]
Yes, It is a mistake. Do appreciate your information!
