### ISSUE TITLE
Full edge remotion in optimization in frame

### ISSUE THREAD

**Issue by rocomanmelli** [Ttoto/FLVIS#5]
I am running your system (thank you for sharing it) on my own data and can't avoid this problem of full edge remotion while performing the in frame optimization:
```
virtual bool g2o::SparseOptimizer::initializeOptimization(g2o::HyperGraph::VertexSet&, int): Attempt to initialize an empty graph
/opt/ros/kinetic/lib/nodelet/nodelet: line 1:   289 Segmentation fault      (core dumped) $0 $@
```
Do you have any idea of what could be causing this problem? I have invested more than a week checking the code and trying to figure out how to solve it but none of the ideas that I came up with helped me out.

**Comment by Ttoto** [comment]
I have never come across this situation before. I think there may be sth wrong with your g2o installation.
Have you tried the EuRoC dataset or our provided rosbag (named:melab_sn943222072828.bag)?

**Comment by zouyajing** [comment]
I reproduced the error before. 

The pose are solved twice in the frame optimization.
If g2o provides very bad pose estimation in the first solver, it will delete all the edges and then start the second solver, which will initialize an empty graph.

For me, it happened when optical flow tracking is too bad and feature matching is totally wrong. My solution is to skip the frame if the quality of optical flow tracking is bad.

**Comment by rocomanmelli** [comment]
Exactly! That was what I thought. However, I have done some tests monitoring the average error reported in `err` variable by `cv::calcOpticalFlowPyrLK` in lkorb_tracking.cpp and I did not find anything strange till it just throws the g2o error. I have also saved the images with the landmarks on them and nothing seems to change drastically. And there is not anything abnormal in the differences between `pnp_inlier_cnt`, `F_inlier_cnt` and `of_inlier_cnt`.

**Comment by Ttoto** [comment]
> Exactly! That was what I thought. However, I have done some tests monitoring the average error reported in `err` variable by `cv::calcOpticalFlowPyrLK` in lkorb_tracking.cpp and I did not find anything strange till it just throws the g2o error. I have also saved the images with the landmarks on them and nothing seems to change drastically. And there is not anything abnormal in the differences between `pnp_inlier_cnt`, `F_inlier_cnt` and `of_inlier_cnt`.

Hello, @rocomanmelli we have revise the inframe optimization workflow. The bug has been fixed. #6

**Comment by rocomanmelli** [comment]
Great! Now the system runs the entire rosbags. Thank you.
