### ISSUE TITLE
Attempt to initialize an empty graph Segmentation fault      (core dumped)

### ISSUE THREAD

**Issue by FaboNo** [Ttoto/FLVIS#6]
First of all, thank you for sharing this work. I am evaluating different VSLAM for my research and I encounter the following error:

```
tracking: 48|50|113
tracking: 67|67|85
tracking: 61|63|82
tracking: 60|63|79
tracking: 58|60|79
tracking: 58|59|76
tracking: 65|86|95
tracking: 62|95|107
tracking: 66|66|66
tracking: 64|65|65
tracking: 62|63|63
tracking: 61|63|63
tracking: 62|63|63
tracking: 60|62|63
tracking: 53|62|67
tracking: 51|121|136
tracking: 42|139|151
virtual bool g2o::SparseOptimizer::initializeOptimization(g2o::HyperGraph::VertexSet&, int): Attempt to initialize an empty graph
/opt/ros/kinetic/lib/nodelet/nodelet: line 1:  7929 Segmentation fault      (core dumped) $0 $@
[flvis_nodelet_manager-3] process has died [pid 7927, exit code 139, cmd bash -c sleep 0; $0 $@ /opt/ros/kinetic/lib/nodelet/nodelet manager __name:=flvis_nodelet_manager __log:=/home/fabrice/.ros/log/bd569f54-0f88-11eb-9699-88b1116f3669/flvis_nodelet_manager-3.log].
log file: /home/fabrice/.ros/log/bd569f54-0f88-11eb-9699-88b1116f3669/flvis_nodelet_manager-3*.log
[ INFO] [1602836582.269961107]: Bond broken, exiting
[ INFO] [1602836582.366583719]: Bond broken, exiting
[ INFO] [1602836582.374452665]: Bond broken, exiting
[LoopClosingNodeletClass_loader-6] process has finished cleanly
log file: /home/fabrice/.ros/log/bd569f54-0f88-11eb-9699-88b1116f3669/Loo
pClosingNodeletClass_loader-6*.log
[TrackingNodeletClass_loader-4] process has finished cleanly
```

![flvis](https://user-images.githubusercontent.com/31440972/96234703-12386c80-0f9a-11eb-816c-0ba71e047972.png)

Do you have any idea why it happens? Or where do  I have to dig to understand what is going on?

I am running FLVIS on ubuntu 16.04

**Comment by Ttoto** [comment]
OK, I didn't come across this situation before. However, another user does report this issue. #5 
I think we will update the OptimizeInFrame function in optimize_in_frame.cpp
This happened when there exist no inliers after the 1st round optimization. the algorithm will manage to construct the empty optimizer.
Line 74 in optimize_in_frame.cpp `optimizer.initializeOptimization();`     
This will trigger the G2O error.

What is the resolution of your input image?

**Comment by FaboNo** [comment]
@Ttoto thank you for your answer. The images are 640x480 at 30Hz

Before that I was able to achieve a run in our lab, and the result was not really good, I mean a large drift in Z (altitude) and in (x, y) - almost 2 metersa way from the home position when I get back to it after a walk of 20 meters. Unfortuately I did not make a copy of the screen. But do you have any idea of what may cause such a drift and which parameters need to be tuned? I noticed that there is no noise values provided in the parameters but I guess it is because you focussed on the D435i mainly.

Thank you again for sharing your code!

**Comment by Ttoto** [comment]
> @Ttoto thank you for your answer. The images are 640x480 at 30Hz
> 
> Before that I was able to achieve a run in our lab, and the result was not really good, I mean a large drift in Z (altitude) and in (x, y) - almost 2 metersa way from the home position when I get back to it after a walk of 20 meters. Unfortuately I did not make a copy of the screen. But do you have any idea of what may cause such a drift and which parameters need to be tuned? I noticed that there is no noise values provided in the parameters but I guess it is because you focussed on the D435i mainly.
> 
> Thank you again for sharing your code!

The 640x480 is OK, as we set the reprojection inlier-outlier threshold to 3 pixels.
2-meter translation error of a 20-meter walk is far more too large. According to our experience, in the indoor environment, the translation error should be about 0.1~0.4 meters(depends on the environment).
Please have a check of the config files. Are you using the D435/D435i? If so, you should copy your camera parameters(fx,fy,cx,cy) into the config file.
In our workflow, you don't need to set the noise density of the IMU sensor. The visual-inertial fusion is carried out by the feed-back loop.

**Comment by FaboNo** [comment]
@Ttoto can you tell me where did you set up the  reprojection inlier-outlier threshold? I will see if I play with some parameters I can avoid the segmentation fault... because in my case it is systematic after some time. 
Did you recalibrate the D435i or rely only on the camera_info data? 

A question quite different, I noticed that you have an octomap_feeder function. Does it mean that you tested it with Octomap as well (point clouds)?

Thanks again for your help

**Comment by Ttoto** [comment]
> @Ttoto can you tell me where did you set up the reprojection inlier-outlier threshold? I will see if I play with some parameters I can avoid the segmentation fault... because in my case it is systematic after some time.
> Did you recalibrate the D435i or rely only on the camera_info data?
> 
> A question quite different, I noticed that you have an octomap_feeder function. Does it mean that you tested it with Octomap as well (point clouds)?
> 
> Thanks again for your help

I will work on this issue. I believe I can push it before **this Friday**!
The update will cover the following features:
* add the inlier-outlier threshold as parameters in the config file 
* revise the workflow of optimize_in_frame.cpp to avoid the "Segmentation Fault" error
* support the d435i sensor running in stereo mode

Yes, we have tested it with the Octomap and other mapping kits before. 
At 2:30 of this video, we test this pose estimation kit in the simulation environment and construct the map.
https://www.youtube.com/watch?v=sKkA5f62P6g&feature=youtu.be

**Comment by Ttoto** [comment]
Updated!
I revised the workflow, if the in_frame_ba is failed, It will skip the ba and use the pose from solvePnPRansac

I did not put the threshold into the config file. you can change it to a larger value throut changing the parameter of these three functions in **lkorb_tracking.cpp**. By default the SH is 3.0.
`cv::findFundamentalMat(from_p2d_undistort, tracked_p2d_undistort,
                           cv::FM_RANSAC, 3.0, 0.99, mask_F_consistant);
cv::solvePnPRansac(p3d,p2d,K0_rect,D0_rect,
                           r_,t_,true,100,3.0,0.99,inliers,cv::SOLVEPNP_ITERATIVE);
cv::solvePnPRansac(p3d,p2d,K0_rect,D0_rect,
                           r_,t_,false,100,3.0,0.99,inliers,cv::SOLVEPNP_P3P);`

**Comment by FaboNo** [comment]
@Ttoto I ran both depth and stereo launch files and I got the same error which is:

```
tracking: 70|72|120
tracking: 80|82|141
tracking: 81|83|148
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
/opt/ros/kinetic/lib/nodelet/nodelet: line 1:  3291 Aborted                 (core dumped) $0 $@
[flvis_nodelet_manager-4] process has died [pid 3284, exit code 134, cmd bash -c sleep 0; $0 $@ /opt/ros/kinetic/lib/nodelet/nodelet manager __name:=flvis_nodelet_manager __log:=/home/fabrice/.ros/log/ae4b6328-145b-11eb-9fc9-88b1116f3669/flvis_nodelet_manager-4.log].
log file: /home/fabrice/.ros/log/ae4b6328-145b-11eb-9fc9-88b1116f3669/flvis_nodelet_manager-4*.log
[ INFO] [1603367025.706939345]: Bond broken, exiting
[TrackingNodeletClass_loader-5] process has finished cleanly
log file: /home/fabrice/.ros/log/ae4b6328-145b-11eb-9fc9-88b1116f3669/TrackingNodeletClass_loader-5*.log
^C[camera/realsense2_camera-3] killing on exit
[camera/vo_manager-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```
If you want I can record a bag and post it on google drive

**Comment by Ttoto** [comment]
> @Ttoto I ran both depth and stereo launch files and I got the same error which is:
> 
> ```
> tracking: 70|72|120
> tracking: 80|82|141
> tracking: 81|83|148
> terminate called after throwing an instance of 'std::out_of_range'
>   what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
> /opt/ros/kinetic/lib/nodelet/nodelet: line 1:  3291 Aborted                 (core dumped) $0 $@
> [flvis_nodelet_manager-4] process has died [pid 3284, exit code 134, cmd bash -c sleep 0; $0 $@ /opt/ros/kinetic/lib/nodelet/nodelet manager __name:=flvis_nodelet_manager __log:=/home/fabrice/.ros/log/ae4b6328-145b-11eb-9fc9-88b1116f3669/flvis_nodelet_manager-4.log].
> log file: /home/fabrice/.ros/log/ae4b6328-145b-11eb-9fc9-88b1116f3669/flvis_nodelet_manager-4*.log
> [ INFO] [1603367025.706939345]: Bond broken, exiting
> [TrackingNodeletClass_loader-5] process has finished cleanly
> log file: /home/fabrice/.ros/log/ae4b6328-145b-11eb-9fc9-88b1116f3669/TrackingNodeletClass_loader-5*.log
> ^C[camera/realsense2_camera-3] killing on exit
> [camera/vo_manager-2] killing on exit
> [rosout-1] killing on exit
> [master] killing on exit
> shutting down processing monitor...
> ... shutting down processing monitor complete
> done
> ```
> 
> If you want I can record a bag and post it on google drive

Definitely, that would be great!

**Comment by FaboNo** [comment]
@Ttoto  please find enclosed two bag files: one with stereo (camera/imu camera/infra1/image_rect_raw camera/infra2/image_rect_raw) and the second one has one more topic /camera/depth/camera_rect_raw

https://drive.google.com/file/d/1sn86SQSHwwBdbHYHIstwwGYKo4yBmmo1/view?usp=sharing

https://drive.google.com/file/d/1WDmKPbhLsg8uOTj04aY1tjU6GeA3Urwk/view?usp=sharing

Hope that you can download them - let me know

**Comment by Ttoto** [comment]
Can u give me the camera parameters? I will evaluate the bag tomorrow.

**Comment by FaboNo** [comment]
@Ttoto  Actually the first two bags I gave you have been done with your parameters.

The second two bags (myparam1 and myparam2) - with the same error - have been done with the following parameters:

cam0_intrinsics: [381.82470703125, 381.82470703125, 319.0743408203125, 237.6382293701172]#fx fy cx cy
cam0_distortion_coeffs: [0.01067,-0.00792,0.00256,0.00137]#k1 k2 r1 r2
T_imu_cam0:
[ 0.0,  0.0,  1.0,  0.0,
 -1.0,  0.0,  0.0,  0.0,
  0.0, -1.0,  0.0,  0.0,
  0.0,  0.0,  0.0,  1.0]
cam1_intrinsics: [381.82470703125, 381.82470703125, 319.0743408203125, 237.6382293701172]#fx fy cx cy
cam1_distortion_coeffs: [0.00843,-0.00585,0.00234,0.00091]#k1 k2 r1 r2
T_cam0_cam1:
[ 1.0,  0.0,  0.0,  0.05,
  0.0,  1.0,  0.0,  0.0,
  0.0,  0.0,  1.0,  0.0,
  0.0,  0.0,  0.0,  1.0]

For these bags, I used the flvis_d435i_stereo.launch file.

Here are the links of the bags with my parameters:

https://drive.google.com/file/d/1Um752f4_i6VEngGW8kkBNXSH-qDGVlBg/view?usp=sharing

https://drive.google.com/file/d/1FnHpWKNjteH4yl1dQXCj9286I5puk4XX/view?usp=sharing

**Comment by Ttoto** [comment]
> @Ttoto Actually the first two bags I gave you have been done with your parameters.
> 
> The second two bags (myparam1 and myparam2) - with the same error - have been done with the following parameters:
> 
> cam0_intrinsics: [381.82470703125, 381.82470703125, 319.0743408203125, 237.6382293701172]#fx fy cx cy
> cam0_distortion_coeffs: [0.01067,-0.00792,0.00256,0.00137]#k1 k2 r1 r2
> T_imu_cam0:
> [ 0.0, 0.0, 1.0, 0.0,
> -1.0, 0.0, 0.0, 0.0,
> 0.0, -1.0, 0.0, 0.0,
> 0.0, 0.0, 0.0, 1.0]
> cam1_intrinsics: [381.82470703125, 381.82470703125, 319.0743408203125, 237.6382293701172]#fx fy cx cy
> cam1_distortion_coeffs: [0.00843,-0.00585,0.00234,0.00091]#k1 k2 r1 r2
> T_cam0_cam1:
> [ 1.0, 0.0, 0.0, 0.05,
> 0.0, 1.0, 0.0, 0.0,
> 0.0, 0.0, 1.0, 0.0,
> 0.0, 0.0, 0.0, 1.0]
> 
> For these bags, I used the flvis_d435i_stereo.launch file.
> 
> Here are the links of the bags with my parameters:
> 
> https://drive.google.com/file/d/1Um752f4_i6VEngGW8kkBNXSH-qDGVlBg/view?usp=sharing
> 
> https://drive.google.com/file/d/1FnHpWKNjteH4yl1dQXCj9286I5puk4XX/view?usp=sharing

It can run on my computer with the default parameters and your paprameters. Please check out this link: [youtube](https://youtu.be/quBJ0_BNiSA)
when using your parameter
cam0_intrinsics: [381.82470703125, 381.82470703125, 319.0743408203125, 237.6382293701172]#fx fy cx cy
cam0_distortion_coeffs: [0.0, 0.0, 0.0, 0.0]#k1 k2 r1 r2
cam1_intrinsics: [381.82470703125, 381.82470703125, 319.0743408203125, 237.6382293701172]#fx fy cx cy
cam1_distortion_coeffs: [0.0, 0.0, 0.0, 0.0]#k1 k2 r1 r2
I set all distortion to 0 (as far as I know, the d435i/d435 sensor output the undistort image)
I change to the Line 145 and Line 152 in f2ftracking.cpp to
`if(frameCount<1) return;`
the original workflow skip the first 50 frames.
As you can observe, the error is less than 1 meter.(I think the bag start at the right side of the table and end in the middle)

**Comment by FaboNo** [comment]
@Ttoto  I will correct the two lines tomorrow morning and run new tests. The error was related to this frameCount ? I am reading your paper right now in order to understand your approach which is more "control" oriented.
Regarding loop closure, how is it possible to activate it? I guess you deactivate it because it is usually taking more processing resources.
Thank you

**Comment by FaboNo** [comment]
@Ttoto I modified the two lines you mentioned in your previous post but I am still getting the same error

```
tracking: 91|93|172
tracking: 103|104|169
tracking: 103|105|159
tracking: 89|91|151
tracking: 77|79|147
tracking: 72|75|153
tracking: 57|57|149
tracking: 60|62|133
tracking: 67|69|127
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
/opt/ros/kinetic/lib/nodelet/nodelet: line 1:  5277 Aborted                 (core dumped) $0 $@
[flvis_nodelet_manager-4] process has died [pid 5270, exit code 134, cmd bash -c sleep 0; $0 $@ /opt/ros/kinetic/lib/no
delet/nodelet manager __name:=flvis_nodelet_manager __log:=/home/fabrice/.ros/log/eaff0bec-1764-11eb-af69-88b1116f3669/
flvis_nodelet_manager-4.log].
log file: /home/fabrice/.ros/log/eaff0bec-1764-11eb-af69-88b1116f3669/flvis_nodelet_manager-4*.log
[ INFO] [1603700853.205417328]: Bond broken, exiting
[TrackingNodeletClass_loader-5] process has finished cleanly
log file: /home/fabrice/.ros/log/eaff0bec-1764-11eb-af69-88b1116f3669/TrackingNodeletClass_loader-5*.log
```
Here is the bag file associated with this trial
https://drive.google.com/file/d/1QfUnyRaa63HrQUGfbeQA2E2a0ewZVU9v/view?usp=sharing

Can you, please, tell me the origin of the error (for my understanding), is it related to a std::vector referred to as M?

On the other hand I got this large drift as well (it happens while I do not move the platform):
![flvis_drift](https://user-images.githubusercontent.com/31440972/97152097-b5df0500-1770-11eb-91cb-09931a9ec8cf.png)
And here is the bag file associated with this trial:
https://drive.google.com/file/d/1DBjY9BZvH0BesR66ZJsCmtWk6a3-f4Rw/view?usp=sharing

Thank you again for your support

**Comment by Ttoto** [comment]
> @Ttoto I will correct the two lines tomorrow morning and run new tests. The error was related to this frameCount ? I am reading your paper right now in order to understand your approach which is more "control" oriented.
> Regarding loop closure, how is it possible to activate it? I guess you deactivate it because it is usually taking more processing resources.
> Thank you

No, the error is not related to the frameCount. I will discuss with my workmate Rick and check it out. I can not represent such an error on my computer. I will try to do more experiments. 
Loop closure can be active by uncommenting the launch file. However, loop closure only support the D435i working in the depth mode(one image and one depth image as an input)

**Comment by Ttoto** [comment]
> @Ttoto I modified the two lines you mentioned in your previous post but I am still getting the same error
> 
> ```
> tracking: 91|93|172
> tracking: 103|104|169
> tracking: 103|105|159
> tracking: 89|91|151
> tracking: 77|79|147
> tracking: 72|75|153
> tracking: 57|57|149
> tracking: 60|62|133
> tracking: 67|69|127
> terminate called after throwing an instance of 'std::out_of_range'
>   what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
> /opt/ros/kinetic/lib/nodelet/nodelet: line 1:  5277 Aborted                 (core dumped) $0 $@
> [flvis_nodelet_manager-4] process has died [pid 5270, exit code 134, cmd bash -c sleep 0; $0 $@ /opt/ros/kinetic/lib/no
> delet/nodelet manager __name:=flvis_nodelet_manager __log:=/home/fabrice/.ros/log/eaff0bec-1764-11eb-af69-88b1116f3669/
> flvis_nodelet_manager-4.log].
> log file: /home/fabrice/.ros/log/eaff0bec-1764-11eb-af69-88b1116f3669/flvis_nodelet_manager-4*.log
> [ INFO] [1603700853.205417328]: Bond broken, exiting
> [TrackingNodeletClass_loader-5] process has finished cleanly
> log file: /home/fabrice/.ros/log/eaff0bec-1764-11eb-af69-88b1116f3669/TrackingNodeletClass_loader-5*.log
> ```
> 
> Here is the bag file associated with this trial
> https://drive.google.com/file/d/1QfUnyRaa63HrQUGfbeQA2E2a0ewZVU9v/view?usp=sharing
> 
> Can you, please, tell me the origin of the error (for my understanding), is it related to a std::vector referred to as M?
> 
> On the other hand I got this large drift as well (it happens while I do not move the platform):
> ![flvis_drift](https://user-images.githubusercontent.com/31440972/97152097-b5df0500-1770-11eb-91cb-09931a9ec8cf.png)
> And here is the bag file associated with this trial:
> https://drive.google.com/file/d/1DBjY9BZvH0BesR66ZJsCmtWk6a3-f4Rw/view?usp=sharing
> 
> Thank you again for your support

here is the screenshot running your bag on my site:
[office](https://youtu.be/0bUiiyPtIoo)
[on the desk](https://youtu.be/gxhSqtAhxZc)
However, sometimes the estimated trajectory contains a large error. This is because visual tracking is lost at the end of the corridor. 
[office loose tracking at corridor](https://youtu.be/QATrwpZl_RI)
However, I didn't come across the error you mentioned above. I will ask my workmate to test on his environment.

**Comment by FaboNo** [comment]
@Ttoto if you are able to run all the bags without the error I mentioned, it looks like it is a problem with my setup? I used your script to install all the third parties so I should have the same ones.

Do you have any idea from where in the tracking nodelet the error below is triggered?
`what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)`

I am running 16.04 with ROS kinetics. I will updates all the packages. Meantime we will see if the error appears with your workmates'setup.

Thank you for the update

**Comment by zouyajing** [comment]
> @Ttoto if you are able to run all the bags without the error I mentioned, it looks like it is a problem with my setup? I used your script to install all the third parties so I should have the same ones.
> 
> Do you have any idea from where in the tracking nodelet the error below is triggered?
> `what(): vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)`
> 
> I am running 16.04 with ROS kinetics. I will updates all the packages. Meantime we will see if the error appears with your workmates'setup.
> 
> Thank you for the update

Hello, I can represent the error in my computer. We are working on this issue. We will have an update in this week.

**Comment by zouyajing** [comment]
> @Ttoto if you are able to run all the bags without the error I mentioned, it looks like it is a problem with my setup? I used your script to install all the third parties so I should have the same ones.
> 
> Do you have any idea from where in the tracking nodelet the error below is triggered?
> `what(): vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)`
> 
> I am running 16.04 with ROS kinetics. I will updates all the packages. Meantime we will see if the error appears with your workmates'setup.
> 
> Thank you for the update

Hello. We have checked the problem.
It is from a bad pose estimated by cv::solvePnPRansac in Line 167 of lkorb_tracking.cpp.
The bad pose will be sent to OptimizeInFrame::optimize(*curr_frame), and it will not be changed because all the edges are deleted by g2o optimizer.
Then the pose is sent to curr_frame->calReprjInlierOutlier(mean_reprojection_error,outlier_reproject,1.5).
The error appears in Line 76 of camera_frame.cpp. valid_distances is empty as no valid distance is computed based on the bad pose. So we cannot visit it.

We have solved the problem by changing the method of cv::solvePnPRansac from cv::SOLVEPNP_ITERATIVE to cv::SOLVEPNP_P3P. Maybe the initial guess  is not accurate, and leads to the bad pose.

Wish it can help.

**Comment by FaboNo** [comment]
@zouyajing thank you for your message. It helps a lot because I do not have the error anymore as you can see below:
![Capture du 2020-11-04 13-08-59](https://user-images.githubusercontent.com/31440972/98117562-41137580-1eaa-11eb-96c5-1ed7d816efae.png)
However I saw a quite big drift in z value:
![stereo](https://user-images.githubusercontent.com/31440972/98117644-5b4d5380-1eaa-11eb-8bb7-974e5e5e809f.png)

I will try to understand from where it comes.

I will try to use the "close loop" nodelet to see if may have an impact here. By the way do you display something on rviz when a close loop is detected?

On the other hand I noticed that there is a local map nodelet as well. Can you tell me please what it is doing (it is not mentioned in your paper)?

Oh I have one more practical question i will say, when you did your experiments with the drone, did you setup the D435i on a vibration damping support (I guess so)?

Thank you again for your kind support and for this impressive work.

**Comment by Ttoto** [comment]
If you enable the loop closure thread, it will see an loop closure path. When the loop closure is detected. We perform an pose optimization. So the path will have a "jump". You can see this in the video.
Yes, the local map node can publish the sparse point cloud map. (Fig.9 in the paper)
No, actually, when we applied our system on the drone platform. We use the IMU data from the flight control unit instead of d435i. the camera is fixed to the air frame without the damper. The flight control unit is fixed to the air frame with dampers.

**Comment by FaboNo** [comment]
@Ttoto yes I saw that you are using Mavros - we are using it as well - but I am wandering how did you change the imu rate? by default we are receiving the imu_data at 50Hz - which is not enough for the VIO algorithm (I guess)
I do not know why Intel did not provide a better IMU setup with the D435i... probably the new one will be better (hopefully)
Thanks again for your kind support - really appreciate it :)

**Comment by Ttoto** [comment]
> @Ttoto yes I saw that you are using Mavros - we are using it as well - but I am wandering how did you change the imu rate? by default we are receiving the imu_data at 50Hz - which is not enough for the VIO algorithm (I guess)
> I do not know why Intel did not provide a better IMU setup with the D435i... probably the new one will be better (hopefully)
> Thanks again for your kind support - really appreciate it :)

With pleasure~

We boost the IMU update rate to 200 Hz (pixhawk harware) by editing the extras.txt in the sd card.

**Comment by FaboNo** [comment]
Oh great ! I will have a look, can you tell (if you remember) which parameters did you edit? Otherwise I will check on px webpages

From your experience, the Pixhawk IMU is more accurate than the D435i one?

**Comment by Ttoto** [comment]
> Oh great ! I will have a look, can you tell (if you remember) which parameters did you edit? Otherwise I will check on px webpages
> 
> From your experience, the Pixhawk IMU is more accurate than the D435i one?

You can follow this link->https://github.com/mavlink/mavros/issues/1346
Yes, I believe so. And another reason to use the FCU's IMU is that you can directly feed the imu pose to the FCU(through /mavros/vision_pose/pose)
You need to calibrate the extrinsic parameter using [Kalibr](https://github.com/ethz-asl/kalibr)

**Comment by FaboNo** [comment]
thank you for the link - I was looking for this information for a while! 
Sorry to bother you with this question, but under /fs/microsd I do not have any etc/ directory. Did you create one and create the extras.txt inside?
![Capture du 2020-11-06 10-47-34](https://user-images.githubusercontent.com/31440972/98351998-c4090d00-201d-11eb-8f6f-e6c6c19fe3ee.png)

when you say calibrate the extrinsic, you mean calibrate the T_imu_cam0 matrix I guess ?

**Comment by FaboNo** [comment]
@Ttoto Just to say that I created indeed a new directory /etc and enter `echo "mavlink stream -d /dev/ttyACM0 -s HIGHRES_IMU -r 100" > extras.txt` and I can access at the IMU data at 100 HZ. Thanks for this link really!
Regarding the extrinsic can you confirm that this is the T_imu_cam0 matrix which needs to be re-computed?

**Comment by Ttoto** [comment]
> @Ttoto Just to say that I created indeed a new directory /etc and enter `echo "mavlink stream -d /dev/ttyACM0 -s HIGHRES_IMU -r 100" > extras.txt` and I can access at the IMU data at 100 HZ. Thanks for this link really!
> 
> Regarding the extrinsic can you confirm that this is the T_imu_cam0 matrix which needs to be re-computed?
> 
> 

Yes!

**Comment by antithing** [comment]
@Ttoto I am running with a D455 camera in stereo mode and I see the same empty graph error. Was this fixed in the main branch? Thank you very much for making this code available!
