### ISSUE TITLE
Current frame being used twice in viCorrectionFromVision

### ISSUE THREAD

**Issue by rocomanmelli** [Ttoto/FLVIS#7]
This [line](https://github.com/HKPolyU-UAV/FLVIS/blob/c35a34afa2a4771ed63b52d46d423a0842a5e0e1/src/frontend/f2f_tracking.cpp#L303) calls my attention since I would think that `last_frame` should be used instead of `curr_frame`. Could this be a bug or I am missing something?

**Comment by Ttoto** [comment]
Thank you for your comment. I do think this is a bug. We will correct it and update a new version.~
