### ISSUE TITLE
Loosely or tightly-coupled?

### ISSUE THREAD

**Issue by rocomanmelli** [Ttoto/FLVIS#8]
Would you say that your estimator is a loosely or a tightly-coupled approach? I guess it is tightly-coupled but I am not really sure because it is far different from the others.

**Comment by Ttoto** [comment]
In my point of view Loosely-coupled and Tightly-coupled depends on whether the IMU states are included in the system states. And these stated are updated accordingly.
So the answer is yes!
Unlike Kalam Filter or Optimisation based system. In this project we use the feedback-feedforward loops to fuse the IMU & Vision information
