### ISSUE TITLE
Build error 'fatal error: nav_msgs/Odometry.h: No such file or directory'

### ISSUE THREAD

**Issue by bigbellmercy** [Ttoto/FLVIS#9]
Build error 'fatal error: nav_msgs/Odometry.h: No such file or directory' happens when it is build for the first time.

I found a solution as below:
In the CMakeList.txt of MLMapping folder, I added the following sentences:

In find_package(), nav_msgs, visualization_msgs and pcl_ros were added.
In generate_messages(), nav_msgs and visualization_msgs were added.
After that, such errors disappeared and its build succeeded.

FYI, this issue is similar to the following in MLMapping:
https://github.com/HKPolyU-UAV/MLMapping/issues/3

**Comment by BamsaAhmed** [comment]
Hi 
I have the same problem even when follow the above post. the error is :
nav_msgs::OdometryConstPtr: No such file or directory

**Comment by JazzyFeng** [comment]
please add dependency in CMakelist
